# Generated by Django 6.0.1 on 2026-01-27 09:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_product_discount_price_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
