# Generated by Django 6.0.1 on 2026-01-27 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_product_discount_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specification',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='core.product'),
        ),
        migrations.CreateModel(
            name='AccessoryConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('mouse', 'Chuột'), ('keyboard', 'Bàn phím'), ('headphone', 'Tai nghe'), ('screen', 'Màn hình rời'), ('other', 'Khác')], default='other', max_length=20)),
                ('connect_type', models.CharField(help_text='VD: Bluetooth, USB, Wireless', max_length=50, verbose_name='Kết nối')),
                ('is_led_rgb', models.BooleanField(default=False, verbose_name='Có Led RGB không?')),
                ('detail', models.TextField(help_text='Nhập DPI, Switch, Loại dây...', verbose_name='Thông số chi tiết')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='accessory_config', to='core.product')),
            ],
        ),
        migrations.CreateModel(
            name='LaptopConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu', models.CharField(help_text='VD: Intel Core i5 12400H', max_length=100)),
                ('ram', models.CharField(help_text='VD: 16GB DDR4 3200MHz', max_length=50)),
                ('rom', models.CharField(help_text='VD: 512GB SSD NVMe', max_length=100, verbose_name='Ổ cứng')),
                ('vga', models.CharField(max_length=100, verbose_name='Card đồ họa')),
                ('screen', models.CharField(max_length=100, verbose_name='Màn hình')),
                ('battery', models.CharField(blank=True, max_length=50, verbose_name='Pin')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Trọng lượng (kg)')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='laptop_config', to='core.product')),
            ],
        ),
    ]
