# Generated by Django 6.0.1 on 2026-01-29 02:25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_specification_product_accessoryconfig_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['sort_order']},
        ),
        migrations.RemoveField(
            model_name='address',
            name='full_address',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='status',
        ),
        migrations.RemoveField(
            model_name='laptopconfig',
            name='ram',
        ),
        migrations.RemoveField(
            model_name='laptopconfig',
            name='rom',
        ),
        migrations.RemoveField(
            model_name='laptopconfig',
            name='screen',
        ),
        migrations.AddField(
            model_name='address',
            name='district',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='address',
            name='province',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='address',
            name='specific_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='address',
            name='ward',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='brand',
            name='logo_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='min_order_value',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='coupon',
            name='quantity',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='inventory',
            name='sold_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='laptopconfig',
            name='ram_desc',
            field=models.CharField(help_text='VD: 16GB DDR4 3200MHz', max_length=100, null=True, verbose_name='Mô tả RAM'),
        ),
        migrations.AddField(
            model_name='laptopconfig',
            name='ram_gb',
            field=models.PositiveIntegerField(help_text='Dung lượng RAM (số) để lọc. VD: 8, 16', null=True),
        ),
        migrations.AddField(
            model_name='laptopconfig',
            name='screen_desc',
            field=models.CharField(max_length=100, null=True, verbose_name='Chi tiết màn hình'),
        ),
        migrations.AddField(
            model_name='laptopconfig',
            name='screen_size',
            field=models.FloatField(help_text='Kích thước màn hình (inch). VD: 15.6', null=True),
        ),
        migrations.AddField(
            model_name='laptopconfig',
            name='storage_desc',
            field=models.CharField(help_text='VD: 512GB SSD NVMe', max_length=100, null=True, verbose_name='Mô tả ổ cứng'),
        ),
        migrations.AddField(
            model_name='laptopconfig',
            name='storage_gb',
            field=models.PositiveIntegerField(help_text='Dung lượng ổ cứng (GB). VD: 512, 1024', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productimage',
            name='image_video_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='accessoryconfig',
            name='connect_type',
            field=models.CharField(blank=True, max_length=50, verbose_name='Kết nối'),
        ),
        migrations.AlterField(
            model_name='accessoryconfig',
            name='detail',
            field=models.TextField(blank=True, verbose_name='Thông số chi tiết'),
        ),
        migrations.AlterField(
            model_name='accessoryconfig',
            name='is_led_rgb',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='accessoryconfig',
            name='type',
            field=models.CharField(choices=[('mouse', 'Chuột'), ('keyboard', 'Bàn phím'), ('headphone', 'Tai nghe'), ('screen', 'Màn hình rời'), ('vga', 'Card đồ họa'), ('cpu', 'CPU'), ('ram', 'RAM PC'), ('other', 'Khác')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='brand',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount_value',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('pending', 'Chờ xác nhận'), ('processing', 'Đang xử lý'), ('shipped', 'Đang giao'), ('delivered', 'Đã giao'), ('cancelled', 'Đã hủy')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='subtotal',
            field=models.DecimalField(decimal_places=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Thanh toán khi nhận hàng'), ('banking', 'Chuyển khoản ngân hàng'), ('momo', 'Ví Momo'), ('vnpay', 'VNPay')], max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Chờ thanh toán'), ('completed', 'Đã thanh toán'), ('failed', 'Thất bại')], default='pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='Giá khuyến mãi (nếu có)', max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=0, help_text='Giá niêm yết', max_digits=15, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='warranty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.warranty'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image_url',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('admin', 'Admin'), ('staff', 'Staff')], default='user', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product')},
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('user', 'product')},
        ),
        migrations.DeleteModel(
            name='RefundRequest',
        ),
    ]
