# Generated by Django 6.0.1 on 2026-01-29 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_productimage_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_default',
            new_name='is_lap',
        ),
    ]
