# Generated by Django 6.0.1 on 2026-01-29 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_is_default_product_is_lap'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='image_url_feature',
            field=models.URLField(max_length=500, null=True),
        ),
    ]
