# Generated by Django 6.0.1 on 2026-01-29 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_productimage_image_url_feature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image_url_feature',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
