# Generated by Django 6.0.1 on 2026-01-31 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_productimage_image_url_feature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessoryconfig',
            name='detail',
        ),
        migrations.AddField(
            model_name='accessoryconfig',
            name='detail_1',
            field=models.TextField(blank=True, verbose_name='Thông số chi tiết 1'),
        ),
        migrations.AddField(
            model_name='accessoryconfig',
            name='detail_2',
            field=models.TextField(blank=True, verbose_name='Thông số chi tiết 2'),
        ),
        migrations.AddField(
            model_name='accessoryconfig',
            name='detail_3',
            field=models.TextField(blank=True, verbose_name='Thông số chi tiết 3'),
        ),
        migrations.AddField(
            model_name='accessoryconfig',
            name='detail_4',
            field=models.TextField(blank=True, verbose_name='Thông số chi tiết 4'),
        ),
        migrations.AddField(
            model_name='accessoryconfig',
            name='detail_5',
            field=models.TextField(blank=True, verbose_name='Thông số chi tiết 5'),
        ),
        migrations.AlterField(
            model_name='accessoryconfig',
            name='type',
            field=models.CharField(choices=[('mouse', 'Chuột'), ('keyboard', 'Bàn phím'), ('screen', 'Màn hình rời'), ('vga', 'Card đồ họa'), ('cpu', 'CPU'), ('ram', 'RAM PC')], default='other', max_length=20),
        ),
    ]
