# Generated by Django 6.0.1 on 2026-02-02 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_product_is_cpu_product_is_headphone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessoryconfig',
            name='detail_1',
            field=models.TextField(blank=True, max_length=50, verbose_name='Thông số chi tiết 1'),
        ),
        migrations.AlterField(
            model_name='accessoryconfig',
            name='detail_2',
            field=models.TextField(blank=True, max_length=50, verbose_name='Thông số chi tiết 2'),
        ),
        migrations.AlterField(
            model_name='accessoryconfig',
            name='detail_3',
            field=models.TextField(blank=True, max_length=50, verbose_name='Thông số chi tiết 3'),
        ),
        migrations.AlterField(
            model_name='accessoryconfig',
            name='detail_4',
            field=models.TextField(blank=True, max_length=50, verbose_name='Thông số chi tiết 4'),
        ),
        migrations.AlterField(
            model_name='accessoryconfig',
            name='detail_5',
            field=models.TextField(blank=True, max_length=50, verbose_name='Thông số chi tiết 5'),
        ),
    ]
