# Generated by Django 6.0.1 on 2026-02-11 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_accessoryconfig_detail_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='receiver_name',
        ),
        migrations.RemoveField(
            model_name='address',
            name='receiver_phone',
        ),
        migrations.RemoveField(
            model_name='address',
            name='specific_address',
        ),
        migrations.AddField(
            model_name='address',
            name='district_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='province_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='street_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='ward_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='province',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='ward',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
